version: '3.8'

services:
  redis:
    container_name: telegram-redis
    image: 'redis:alpine'
    ports:
      - 6379:6379
    extra_hosts:
      - "host.docker.internal:host-gateway"
  app:
    image: staking-alert
    build: 
      context: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
  worker:
    container_name: telegram-worker
    image: staking-alert
    command: rq worker -u redis://redis:6379/0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - app
      - redis